project:
  type: website

website:
  title: "tylar.info"
  navbar:
    right:
      - text: About the Author
        href: index/index.html
      # - about.qmd
      #- text: blog
      #  href: blog.qmd

      - text: IMaRS
        href: https://imars.usf.edu

      - icon: github
        href: https://github.com/7yl4r
      #- icon: twitter
      #  href: https://twitter.com/7yl4r
format:
  html:
    theme: cosmo
    css: styles.css
resources:
  - "index/css/*"
  - "index/js/*"
  - "index/js/fancybox/*"
  - "index/js/owl-carousel/*"
  - "index/images/*"
